// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "Your_Supabase_URL"; // Replace with your actual Supabase URL
const SUPABASE_PUBLISHABLE_KEY = "Your_Supabase_Publishable_Key"; // Replace with your actual Supabase publishable key

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);